'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Configuration.SettingsProviderAttribute(GetType(ScanExact.PortableSettingsProvider)),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute(""),
         Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>
        Public Property DeviceID() As String
            Get
                Return CType(Me("DeviceID"),String)
            End Get
            Set
                Me("DeviceID") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Configuration.SettingsProviderAttribute(GetType(ScanExact.PortableSettingsProvider)),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True"),
         Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>
        Public Property PrintColor() As Boolean
            Get
                Return CType(Me("PrintColor"),Boolean)
            End Get
            Set
                Me("PrintColor") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Configuration.SettingsProviderAttribute(GetType(ScanExact.PortableSettingsProvider)),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("100, 100"),
         Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>
        Public Property Location() As Global.System.Drawing.Point
            Get
                Return CType(Me("Location"),Global.System.Drawing.Point)
            End Get
            Set
                Me("Location") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Configuration.SettingsProviderAttribute(GetType(ScanExact.PortableSettingsProvider)),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False"),
         Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>
        Public Property StoreLocation() As Boolean
            Get
                Return CType(Me("StoreLocation"),Boolean)
            End Get
            Set
                Me("StoreLocation") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Configuration.SettingsProviderAttribute(GetType(ScanExact.PortableSettingsProvider)),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("(Default)"),
         Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return CType(Me("Culture"),Global.System.Globalization.CultureInfo)
            End Get
            Set
                Me("Culture") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Configuration.SettingsProviderAttribute(GetType(ScanExact.PortableSettingsProvider)),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True"),
         Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>
        Public Property RememberSettings() As Boolean
            Get
                Return CType(Me("RememberSettings"),Boolean)
            End Get
            Set
                Me("RememberSettings") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Configuration.SettingsProviderAttribute(GetType(ScanExact.PortableSettingsProvider)),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute(""),
         Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>
        Public Property DefaultPrinter() As String
            Get
                Return CType(Me("DefaultPrinter"),String)
            End Get
            Set
                Me("DefaultPrinter") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Configuration.SettingsProviderAttribute(GetType(ScanExact.PortableSettingsProvider)),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute(""),
         Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>
        Public Property DefaultScanner() As String
            Get
                Return CType(Me("DefaultScanner"),String)
            End Get
            Set
                Me("DefaultScanner") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Configuration.SettingsProviderAttribute(GetType(ScanExact.PortableSettingsProvider)),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("A4"),
         Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>
        Public Property PrinterSize() As String
            Get
                Return CType(Me("PrinterSize"),String)
            End Get
            Set
                Me("PrinterSize") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Configuration.SettingsProviderAttribute(GetType(ScanExact.PortableSettingsProvider)),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False"),
         Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>
        Public Property CustomCulture() As Boolean
            Get
                Return CType(Me("CustomCulture"),Boolean)
            End Get
            Set
                Me("CustomCulture") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Configuration.SettingsProviderAttribute(GetType(ScanExact.PortableSettingsProvider)),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>
        Public Property LastScanSettings() As Global.ScanExact.ScanSettings
            Get
                Return CType(Me("LastScanSettings"), Global.ScanExact.ScanSettings)
            End Get
            Set
                Me("LastScanSettings") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Configuration.SettingsProviderAttribute(GetType(ScanExact.PortableSettingsProvider)),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("2011-01-01"),
         Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>
        Public Property LastVersionCheck() As Date
            Get
                Return CType(Me("LastVersionCheck"), Date)
            End Get
            Set
                Me("LastVersionCheck") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Configuration.SettingsProviderAttribute(GetType(ScanExact.PortableSettingsProvider)),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True"),
         Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>
        Public Property CheckForUpdates() As Boolean
            Get
                Return CType(Me("CheckForUpdates"), Boolean)
            End Get
            Set
                Me("CheckForUpdates") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Configuration.SettingsProviderAttribute(GetType(ScanExact.PortableSettingsProvider)),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False"),
         Global.System.Configuration.SettingsManageabilityAttribute(Global.System.Configuration.SettingsManageability.Roaming)>
        Public Property Silent() As Boolean
            Get
                Return CType(Me("Silent"), Boolean)
            End Get
            Set
                Me("Silent") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Configuration.SettingsProviderAttribute(GetType(ScanExact.PortableSettingsProvider)),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property Center() As Boolean
            Get
                Return CType(Me("Center"), Boolean)
            End Get
            Set
                Me("Center") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Configuration.SettingsProviderAttribute(GetType(ScanExact.PortableSettingsProvider)),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property PDFAskWhereToSave() As Boolean
            Get
                Return CType(Me("PDFAskWhereToSave"), Boolean)
            End Get
            Set
                Me("PDFAskWhereToSave") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Configuration.SettingsProviderAttribute(GetType(ScanExact.PortableSettingsProvider)),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property PDFOpenAfterAcquisition() As Boolean
            Get
                Return CType(Me("PDFOpenAfterAcquisition"), Boolean)
            End Get
            Set
                Me("PDFOpenAfterAcquisition") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Configuration.SettingsProviderAttribute(GetType(ScanExact.PortableSettingsProvider)),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property FileOpenAfterAcquisition() As Boolean
            Get
                Return CType(Me("FileOpenAfterAcquisition"), Boolean)
            End Get
            Set
                Me("FileOpenAfterAcquisition") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Configuration.SettingsProviderAttribute(GetType(ScanExact.PortableSettingsProvider)),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property FileAskWhereToSave() As Boolean
            Get
                Return CType(Me("FileAskWhereToSave"), Boolean)
            End Get
            Set
                Me("FileAskWhereToSave") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Configuration.SettingsProviderAttribute(GetType(ScanExact.PortableSettingsProvider)),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property FileSavePath() As String
            Get
                Return CType(Me("FileSavePath"), String)
            End Get
            Set
                Me("FileSavePath") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Configuration.SettingsProviderAttribute(GetType(ScanExact.PortableSettingsProvider)),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property PDFSavePath() As String
            Get
                Return CType(Me("PDFSavePath"),String)
            End Get
            Set
                Me("PDFSavePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("haarden-sql\mssql2017")>  _
        Public Property SQLserver() As String
            Get
                Return CType(Me("SQLserver"),String)
            End Get
            Set
                Me("SQLserver") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://haarden-sql:8010/service")>  _
        Public Property ServiceURI() As String
            Get
                Return CType(Me("ServiceURI"),String)
            End Get
            Set
                Me("ServiceURI") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("011")>  _
        Public Property Administrations() As String
            Get
                Return CType(Me("Administrations"),String)
            End Get
            Set
                Me("Administrations") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IsConnectionToExactSucceeded() As Boolean
            Get
                Return CType(Me("IsConnectionToExactSucceeded"),Boolean)
            End Get
            Set
                Me("IsConnectionToExactSucceeded") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ScanExact.My.MySettings
            Get
                Return Global.ScanExact.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
